# Generated by Django 6.0.1 on 2026-01-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_semester_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightpass',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
