# Generated by Django 6.0.1 on 2026-01-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_nightpass_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nightpass',
            options={'ordering': ('-date',), 'verbose_name_plural': 'Night Passes'},
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
