# Generated by Django 6.0.1 on 2026-02-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_nightpass_options_alter_nightpass_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nightpass',
            old_name='check_in_time',
            new_name='library_in_time',
        ),
        migrations.RenameField(
            model_name='nightpass',
            old_name='check_out_time',
            new_name='library_out_time',
        ),
        migrations.RemoveField(
            model_name='nightpass',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='nightpass',
            name='check_out',
        ),
        migrations.AddField(
            model_name='nightpass',
            name='current_step',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='nightpass',
            name='pass_type',
            field=models.CharField(choices=[('HOSTEL', 'Starting from Hostel (5 Scans)'), ('OUTSIDE', 'Starting from Outside (3 Scans)')], default='HOSTEL', max_length=10),
        ),
    ]
