# Generated by Django 5.2.11 on 2026-02-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_nightpass_options_alter_nightpass_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
