# Generated by Django 6.0.1 on 2026-02-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_options'),
        ('users', '0015_rename_check_in_time_nightpass_library_in_time_and_more'),
    ]

    operations = [
    ]
