# Generated by Django 6.0.1 on 2026-03-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20260219_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='campus_resource',
        ),
    ]
