# Generated by Django 5.2.8 on 2026-03-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_nightpass_violation_fields_and_security_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightpass',
            name='pass_type',
            field=models.CharField(choices=[('HOSTEL', 'Starting from Hostel (5 Scans)'), ('OUTSIDE', 'Starting from Outside (3 Scans)')], default='HOSTEL', max_length=20),
        ),
    ]
