# Generated by Django 6.0.1 on 2026-02-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightpass', '0004_hostel_max_students_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusresource',
            name='default_pass_type',
            field=models.CharField(choices=[('hostel', 'Starting from Hostel (5 Scans)'), ('outside', 'Starting from Outside (3 Scans)')], default='hostel', help_text='Defines if the pass starts at the hostel gate or directly at the resource.', max_length=20),
        ),
    ]
