# Generated by Django 6.0.1 on 2026-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightpass', '0005_campusresource_default_pass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusresource',
            name='default_pass_type',
            field=models.CharField(choices=[('HOSTEL', 'Starting from Hostel (5 Scans)'), ('OUTSIDE', 'Starting from Outside (3 Scans)')], default='HOSTEL', help_text='Set to OUTSIDE for the 3-scan Library system.', max_length=20),
        ),
    ]
