# Generated by Django 6.1.1 on 2026-09-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightpass', '0007_alter_hostel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusresource',
            name='audience_type',
            field=models.CharField(choices=[('HOSTELLER', 'Hosteller'), ('DAY_SCHOLAR', 'Day Scholar')], default='HOSTELLER', max_length=20),
        ),
        migrations.AlterField(
            model_name='campusresource',
            name='default_pass_type',
            field=models.CharField(choices=[('HOSTEL', 'Starting from Hostel (5 Scans)'), ('OUTSIDE', 'Starting from Outside (3 Scans)'), ('DAY_SCHOLAR', 'Day Scholar (2 Scans)')], default='HOSTEL', help_text='Set to OUTSIDE for the 3-scan Library system.', max_length=20),
        ),
    ]
